config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    get 'home/index', to: 'home#index', as: 'home_index'
    get 'home/barriers', to: 'home#barriers', as: 'home_barriers'
    get 'home/job_sheet', to: 'home#job_sheet', as: 'job_sheet'
    get 'home/route_setting', to: 'home#route_setting', as: 'route_setting'
    get 'home/fetch_regions', to: 'home#fetch_regions', as: 'fetch_regions'
    post 'home/selected_regions', to: 'home#selected_regions', as: 'selected_regions'
    get 'home/geocode', to: 'home#geocode', as: 'geocode'
    post '/upload_kmz', to: 'kmz#upload'
    post '/barriers', to: 'barriers#create', format: :js
    get '/barriers', to: 'barriers#index', as: 'barrier_index'
    delete '/barriers', to: 'barriers#destroy', as: 'destroy'
    post '/job_sheets', to: 'job_sheets#create'
    post '/generate_pdf', to: 'job_sheets#generate_pdf'
    get 'home/get_directions', to: 'home#get_directions'
    post 'home/save_directions', to: 'home#save_directions'
  end

  namespace :user do
    get 'home/index', to: 'home#index', as: 'home_index'
    get 'home/geocode', to: 'home#geocode', as: 'geocode'
    get 'home/get_directions', to: 'home#get_directions'
    get 'home/job_sheet', to: 'home#job_sheet', as: 'job_sheet'
  end

  authenticated :admin do
    root to: 'admin/home#index', as: :authenticated_admin_root
  end

  authenticated :user do
    root to: 'user/home#index', as: :authenticated_user_root
  end

  unauthenticated do
    root to: 'user/home#index'
  end
end

app/views/shared/_barriers.html.erb
<section class="top_section p-2">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="col-md-5">
        <%= image_tag('logo.jpg', class: 'img-fluid') %>
      </div>
      <div class="col-md-7 line">
        <div class="d-block">
          <p class="mb-0 text-center my-2 fs-3 text-white">
            START A NEW ROUTE
          </p>
          <div class="d-flex mt-2">
            <div style="width: 85%;">
          <!-- For the Start location -->
            <div class="d-flex align-items-center">
              <p class="start_txt">Start</p>
              <span class="depot_text">
                <%= link_to '#', id: 'start-depot-link', data: { yard_address: '8 Ivan Street Arundel.' }, class: 'prevent-default text-white' do %>
                  Depot
                <% end %>
              </span>
              <%= text_field_tag 'start_location', nil, class: 'form-control', id: 'start-location-input', placeholder: 'Enter or click Depot' %>
              <span class="find_txt">
                <%= link_to '#', id: 'start-find-link', class: "text-white" do %>
                  Find
                <% end %>
              </span>
            </div>
            <!-- For the End location -->
            <div class="d-flex align-items-center mt-2">
              <p class="start_txt">End</p>
              <span class="depot_text">
                <%= link_to '#', id: 'end-depot-link', data: { yard_address: '8 Ivan Street Arundel.' }, class: 'prevent-default text-white' do %>
                  Depot
                <% end %>
              </span>
              <%= text_field_tag 'end_location', nil, class: 'form-control', id: 'end-location-input', placeholder: 'Enter or click Depot' %>
              <span class="find_txt">
                <%= link_to '#', id: 'end-find-link', class: "text-white" do %>
                  Find
                <% end %>
              </span>
            </div>
          </div>
          <div style="width: 15%;" class="">
              <button class="btn begin_btn" type="button">BEGIN</button>
          </div>
      </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="rounte_section p-2">
<div class="container-fluid">
  <div class="row">
    <div id="map" style="height: 400px;", class="col-md-8"></div>
    <div class="col-md-4 p-0  bg-white position-relative">
      <div class="route-directions">
        <h2>ROUTE DIRECTIONS</h2>
          <p id="directions-content" style="height:274px; overflow-y: auto;"></p>
        <h3 class="mb-0 open-modal-job-sheet">Build job Sheet</h3>
      </div>
    </div>
  </div>
</div>
</section>

<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-body" id="modal-content-container">
        <!-- Content will be loaded here dynamically -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" id="close-modal-button" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Include necessary libraries -->
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>

<!-- Map initialization -->

<script>
 var map;
 var locations = [];
 var allDirections = [];  // Declare outside the loop
 var selectedParamsRegions = []

  $(document).ready(function() {
    // Initialize the map once
    map = L.map('map').setView([51.505, -0.09], 13);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; OpenStreetMap contributors'
    }).addTo(map);

    // Populate locations array from server data

    selectedParamsRegions = <%= @selected_regions.to_json.html_safe %>;
    <% @locations.each do |location| %>
      
      var markerColor = '<%= location[:barrier] ? "red" : "red" %>';

      var circleMarker = L.circleMarker([<%= location[:latitude] %>, <%= location[:longitude] %>], {
        radius: 4, // Adjust the size as needed
        color: markerColor,
        fillOpacity: 2
      })
      .addTo(map)
      .bindPopup('<%= location[:region] %>');
      locations.push(circleMarker.getLatLng());
    <% end %>

    // Set map view based on locations
    if (locations.length > 0) {
      map.fitBounds(L.latLngBounds(locations));
    } else {
      map.setView([51.505, -0.09], 13);
    }
  });
</script>

<script>
  var jq = jQuery.noConflict();
  var lastStartSearchMarker = null;
  var lastEndSearchMarker = null;

  jq(document).ready(function () {
    function addMarker(location, address) {
      if (location && location.latitude && location.longitude) {
        var customIcon = L.icon({
          iconUrl: '<%= asset_path('marker-image.png') %>',
          iconSize: [32, 32],
        });
    
        var marker = L.marker([location.latitude, location.longitude], { icon: customIcon }).addTo(map);
        marker.bindPopup(address || '');
        return marker;
      }
      return null;
    }

    function clearMarker(marker) {
      if (marker) {
        map.removeLayer(marker);
      }
    }

    function updateMap(address, isStartDepot) {
      if (address) {
        jq.ajax({
          url: '/user/home/geocode', // Assuming you have a geocode action in your controller
          method: 'GET',
          data: { address: address },
          success: function (data) {
            debugger
            debugger
            if (isStartDepot) {
              clearMarker(lastStartSearchMarker);
              lastStartSearchMarker = addMarker(data, address);
              map.setView([data.latitude, data.longitude], 13);
            } else {
              clearMarker(lastEndSearchMarker);
              lastEndSearchMarker = addMarker(data, address);
              map.setView([data.latitude, data.longitude], 13);
            }
          },
          error: function (xhr, status, error) {
            console.error('Error geocoding address:', error);
            console.log('XHR object:', xhr);
          }
        });
      }
    }

    // Start depot link click event
    $(document).on("click", "#start-depot-link", function() {
      var yardAddress = $(this).data('yard-address');
      $("#start-location-input").val(yardAddress);
    });

    // Find button click event for start depot
    jq('#start-find-link').on('click', function (e) {
      e.preventDefault();
      var address = jq('#start-location-input').val();
      updateMap(address, true);
    });

    // End depot link click end-depot-linkevent
    $(document).on("click", "#end-depot-link", function() {
      var yardAddress = $(this).data('yard-address');
      $("#end-location-input").val(yardAddress);
    });
  
    // Find button click event for end depot
    jq('#end-find-link').on('click', function (e) {
      e.preventDefault();
      var address = jq('#end-location-input').val();
      updateMap(address, false);
    });
    jq('.prevent-default').on('click', function(e) {
      e.preventDefault();
    });
  });
</script>

<script>
  $('.begin_btn').on('click', function () {
    var startLocation = $('#start-location-input').val();
    var endLocation = $('#end-location-input').val();
    
    // Make a POST request to your Rails server
    $.ajax({
      url: '/user/home/get_directions',
      method: 'GET',
      data: { start_location: startLocation, end_location: endLocation, barriers_selected: selectedParamsRegions },
      success: function (data) {
        // Process the directions data and barriers data
        handleDirections(data);
      },
      error: function (error) {
        console.error('Failed to get directions from the server:', error);
      },
    });
  });

  function handleDirections(data) {
    if (data.status === 'OK') {
      var routes = data.routes;
  
      var barrier_coordinates = data.barriers; // Extract barrier_coordinates from the response
      var routePoints = [];    // Declare outside the loop
  
      // Clear existing directions
      allDirections = [];
  
      routes.forEach(function (route, routeIndex) {
        var routeInstructions = [];
  
        route.legs.forEach(function (leg) {
          leg.steps.forEach(function (step) {
            var startLocation = step.start_location;
            var endLocation = step.end_location;
  
            routePoints.push([startLocation.lat, startLocation.lng]);
            routePoints.push([endLocation.lat, endLocation.lng]);
  
            // Check if step.instructions is defined before pushing it
            if (step.html_instructions) {
              // Include the route number and instructions
              var instructions = step.html_instructions;
              routeInstructions.push(instructions);
  
              // Pass barrier_coordinates to updateMapWithDirection
              updateMapWithDirection(startLocation, endLocation, routeIndex, barrier_coordinates);
            }
          });
        });
  
        // Display route number and instructions
        displayRouteInstructions(routeIndex + 1, routeInstructions);
      });
  
      if (routePoints.length > 0) {
        map.fitBounds(routePoints);
      }
  
      // Update the HTML with the new directions
      var directionsContent = allDirections.join('<br>');
      $('#directions-content').html(directionsContent);
    } else {
      console.error('Directions request failed:', data.status);
    }
  }
  

  function updateMapWithDirection(startLocation, endLocation, routeIndex, barriersData) {
    var polyline = L.polyline([
      [startLocation.lat, startLocation.lng],
      [endLocation.lat, endLocation.lng],
    ]).addTo(map);

    polyline._routeIndex = routeIndex;

    var crossesBarriers = checkBarriers(polyline, barriersData);
    if (!crossesBarriers) {
      polyline.setStyle({ color: 'green' });
    }
  }

  function checkBarriers(polyline, barriersData) {
    var polylineCoordinates = polyline.getLatLngs().map(function (latLng) {
      return [latLng.lat, latLng.lng];
    });

    var crossesBarriers = barriersData.some(function (barrierCoordinates) {
      return isPolylineCrossingBarrier(polylineCoordinates, barrierCoordinates);
    });

    return crossesBarriers;
  }

  function isPolylineCrossingBarrier(polylineCoordinates, barrierCoordinates) {
    var [barrierLat, barrierLng] = barrierCoordinates;
    var latitudes = polylineCoordinates.map(function (point) { return point[0]; });
    var longitudes = polylineCoordinates.map(function (point) { return point[1]; });

    var minLat = Math.min.apply(null, latitudes);
    var maxLat = Math.max.apply(null, latitudes);
    var minLng = Math.min.apply(null, longitudes);
    var maxLng = Math.max.apply(null, longitudes);

    return (
      minLat <= barrierLat && barrierLat <= maxLat &&
      minLng <= barrierLng && barrierLng <= maxLng
    );
  }

  function displayRouteInstructions(routeNumber, instructions) {
    allDirections.push("<strong>Route " + routeNumber + "</strong>");

    instructions.forEach(function (instruction) {
      allDirections.push(instruction);
    });
  }
</script>

<script>
  $(document).ready(function() {
    var openModalButton = $('.open-modal-job-sheet');
    var myModal = new bootstrap.Modal($('#myModal'), {
      keyboard: false
    });
    openModalButton.on('click', function() {
      $.ajax({
        url: '<%= user_job_sheet_path %>',
        method: 'GET',
        dataType: 'html',
        data: { start_location: allDirections},
        success: function(data, xhr) {
          $('#modal-content-container').html(data);
          myModal.show();
        },
        error: function(error) {
          console.error('Error fetching content:', error);
        }
      });
    });

    $('#close-modal-button').on('click', function() {
      myModal.hide();
    });
  });
</script>

app/views/shared/_errors.html.erb
<div id="error_explanation">
  <div class="alert alert-danger">
    <% if resource.errors.any? %>
      ERROR: Unable to add new Barrier. Please check all details and try again. Confirm Longitude and Latitude are valid.
    <%else%>
      Barrier add successfully
    <% end %>
  </div>
</div>

app/views/shared/_user_info.html.erb
<% if current_user %>
  <p>Hello <%= current_user&.email %></p><br>
  <p>You are Role: <%= current_user&.role %></p><br>
  <%= link_to "Log Out", destroy_user_session_path, 'data-turbo-method': :delete %>
<% else %>
  <p>You are not signed in</p>
  <p>
    <%= link_to "Sign up", new_user_registration_path %><br>
    <%= link_to "Login", new_user_session_path %>
  </p>
<% end %>

app/views/shared/job_sheet.html.erb
<section class="form_main">
  <p class="text-center bg-black text-white p-2 w-100 mb-0 fw-bold fs-3">
    JOB SHEET
  </p>
  <div class="container-fluid">
    <div class="row">
      <div class= "col-md-12 p-0 mx-auto">
      </div>
      <h2 class='text-start'><span class="fw-bold me-5">JOB DETAILS</span>
        Enter the details for the job sheet below
      </h2>
    </div>
    <div class="row">
      <div class="col-md-12 p-0">
        <div class="box text-start">
          <%= form_for(JobSheet.new, url: admin_generate_pdf_path(format: :pdf), method: 'post') do |form| %>
            <div class="box_main">
              <div class="box_inner_child border-0">
                <p class="text-start fs-5 mb-3"> All of these fields will be on the generated job sheet </p>
                <div class="row">
                  <div class="col-md-6">
                    <div class="mb-3 text-start">
                      <%= form.label :start_address, class: "form-label fw-bold" do %>
                      Start Address:
                      <% end %>
                      <%= form.text_area :start_address, class: "form-control rounded-0", id: "exampleStartAddress" %>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="mb-3 text-start">
                      <%= form.label :end_address, class: "form-label fw-bold" do %>
                      End Address:
                      <% end %>
                      <%= form.text_area :end_address, class: "form-control rounded-0", id: "exampleEndAddress" %>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="mb-3 text-start">
                      <%= form.label :customer_name, class: "form-label fw-bold" do %>
                      Customer Name:
                      <% end %>
                      <%= form.text_field :customer_name, class: "form-control rounded-0", id: "exampleInputPassword1" %>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="mb-3 text-start">
                      <%= form.label :site_contact, class: "form-label fw-bold" do %>
                      Site Contact:
                      <% end %>
                      <%= form.text_field :site_contact, class: "form-control rounded-0", id: "exampleInputPassword1" %>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="mb-3 text-start">
                      <%= form.label :contact_number, class: "form-label fw-bold" do %>
                      Contact Number:
                      <% end %>
                      <%= form.text_field :contact_number, class: "form-control rounded-0", id: "exampleInputPassword1" %>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="mb-3 text-start form-check ps-0">
                      <%= form.label :job_number, class: "form-label fw-bold" do %>
                      Job Number:
                      <% end %>
                      <%= form.text_field :job_number, class: "form-control rounded-0", id: "exampleInputPassword1" %>
                    </div>
                  </div>
                  <div class="mb-3 text-start">
                    <%= form.label :job_instruction, class: "form-label fw-bold" do %>
                    Job Special Instruction:
                    <% end %>
                    <%= form.text_area :job_instruction, class: "form-control rounded-0", id: "exampleInputEmail1", "a  ria-describedby" => "emailHelp" %>
                  </div>
                  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                  <%= form.button 'PROCESS', class: "btn add_btn w-100 p-2 p-lg-2 fw-bold text-white rounded-0", type: 'submit', id: 'process_button' %>
                </div>
              </div>
            </div>
          <% end %> 
        </div>
      </div>
    </div>
    <div id="error-message"></div>
  </div>
</section>


<script>
  start_address = $('#start-location-input').val()
                  $('#exampleStartAddress').val(start_address)
  end_address = $('#end-location-input').val()
                  $('#exampleEndAddress').val(end_address)
  
  $(document).ready(function() {
    $('#process_button').on('click', function(event) {
      var startAddress = $('#exampleStartAddress').val();
      var endAddress = $('#exampleEndAddress').val();
      if (!startAddress.trim() || !endAddress.trim()) {
        event.preventDefault();
        $('#error-message').html('<div class="alert alert-danger" role="alert">Start and end addresses cannot be blank.</div>');
      } else {
        $('#job-sheet-form').submit();
      }
    });
  });                  
</script>