config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    get 'home/index', to: 'home#index', as: 'home_index'
    get 'home/barriers', to: 'home#barriers', as: 'home_barriers'
    get 'home/job_sheet', to: 'home#job_sheet', as: 'job_sheet'
    get 'home/route_setting', to: 'home#route_setting', as: 'route_setting'
    get 'home/fetch_regions', to: 'home#fetch_regions', as: 'fetch_regions'
    post 'home/selected_regions', to: 'home#selected_regions', as: 'selected_regions'
    get 'home/geocode', to: 'home#geocode', as: 'geocode'
    post '/upload_kmz', to: 'kmz#upload'
    post '/barriers', to: 'barriers#create', format: :js
    get '/barriers', to: 'barriers#index', as: 'barrier_index'
    delete '/barriers', to: 'barriers#destroy', as: 'destroy'
    post '/job_sheets', to: 'job_sheets#create'
    post '/generate_pdf', to: 'job_sheets#generate_pdf'
    get 'home/get_directions', to: 'home#get_directions'
    post 'home/save_directions', to: 'home#save_directions'
  end

  namespace :user do
    get 'home/index', to: 'home#index', as: 'home_index'
    get 'home/geocode', to: 'home#geocode', as: 'geocode'
    get 'home/get_directions', to: 'home#get_directions'
    get 'home/job_sheet', to: 'home#job_sheet', as: 'job_sheet'
  end

  authenticated :admin do
    root to: 'admin/home#index', as: :authenticated_admin_root
  end

  authenticated :user do
    root to: 'user/home#index', as: :authenticated_user_root
  end

  unauthenticated do
    root to: 'user/home#index'
  end
end

app/controllers/admin/home_controller.rb
require 'zip'
require 'polylines'

class Admin::HomeController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin_role

  def index
    if params[:upload].present? || params[:regions]
      all_locations = get_kmz_extract_lat_long_region
      selected_regions = params[:regions]
     
      if selected_regions.present?
        @locations = get_locations(selected_regions, all_locations)
        @selected_regions = selected_regions

        user = User.find_by(id: current_user.id)

        user.locations = @locations
        user.save
      else
        @selected_regions = []
        @locations = all_locations
      end
    elsif params[:create_barrier].present?
      coordinates_with_names = Barrier.pluck(:latitude, :longitude, :name)
      result_with_names = format_barriers_response(coordinates_with_names)
      @selected_regions = []
      @locations =  result_with_names
    else
      @selected_regions = []
      @locations = current_user.locations.present? ? hash_response(current_user.locations) : []
    end

    render 'index'
  end
  
  def barriers
    render 'barriers'
  end

  def route_setting
    render 'route_setting'
  end

  def job_sheet
    render 'shared/job_sheet'
  end

  def add_barriers
    @barrier = Barrier.new(barrier_params)

    respond_to do |format|
      if @barrier.save
        format.js   # Render create.js.erb for AJAX response on success
      else
        format.js { render 'admin/barriers/error', status: :unprocessable_entity } # Render error.js.erb on failure
      end
    end
  end

  def fetch_regions
    if params[:checkboxes].present?
      if (params[:checkboxes].include?("permanent") && params[:checkboxes].include?("government"))
        permanent_barriers = fetch_regions_for_permanent_barriers
        gov_barriers = fetch_regions_for_government_barriers
        @locations = permanent_barriers + gov_barriers
      elsif params[:checkboxes].include?("permanent")
        @locations = fetch_regions_for_permanent_barriers
      elsif params[:checkboxes].include?("government")
        @locations = fetch_regions_for_government_barriers
      else
        @locations = []
      end
    else
      @locations = []
    end

    render json: @locations
  end

  def selected_regions
    
  end

  def geocode
    try = 0
    begin
      yield try
    rescue *exceptions => exc
      try += 1
      try <= 3 ? retry : raise
    end
  end

  def geocode
    result = nil
    retry_count = 0
  
    begin
      result = Geocoder.search(params[:address]).first
    rescue
      if retry_count < 3  # Retry up to 3 times
        retry_count += 1
        sleep(1)  # Wait for 1 second before retrying
        retry
      else
        render json: { error: 'Geocoding failed after multiple attempts' }, status: :unprocessable_entity
        return
      end
    end
  
    if result.nil?
      render json: { error: 'Geocoding failed: no result found' }, status: :unprocessable_entity
      return
    end
  
    coordinates = { latitude: result.latitude, longitude: result.longitude }
    render json: coordinates
  end  

  def get_directions
    start_location = params[:start_location]
    middle_location = params[:middle_location]
    end_location = params[:end_location]

    if params[:barriers_selected].present? || current_user.locations.present?
      if params[:barriers_selected].present?
        @barriers_selected = params[:barriers_selected]
      else
        # Assuming current_user.locations is an array of hashes
        @barriers_selected = current_user.locations.map { |location| location["region"] }.uniq
      end

      all_locations = get_kmz_extract_lat_long_region
      barrier_coordinates = get_locations(@barriers_selected, all_locations)
      barrier_coordinates = barrier_coordinates.map { |entry| [entry[:latitude], entry[:longitude]] }
    else
      barrier_coordinates = []
    end

    all_routes = []

    if start_location.present? && middle_location.present? && end_location.present?
      waypoints = "#{middle_location}"  # No need to optimize waypoints here
      @response_start_to_middle = fetch_route(start_location, end_location, waypoints)
      routes = @response_start_to_middle['routes']
      all_routes.concat(routes)
    elsif start_location.present? && end_location.present?
      @response_start_to_end = fetch_route(start_location, end_location)
      routes = @response_start_to_end['routes']
      all_routes.concat(routes)
    elsif middle_location.present? && end_location.present?
      @response_from_middle_to_end = fetch_route(middle_location, end_location)
      routes = @response_from_middle_to_end['routes']
      all_routes.concat(routes)
    end    
    
    response = [@response_start_to_end, @response_start_to_middle, @response_from_middle_to_end].compact.flatten

    # Check if there is a Response record present
    response_data = Response.where(response_type: "route").last

    if response_data.present?
      # Update the existing Response record
      response_data.response_type = "route"
      response_data.json_file.attach(io: StringIO.new(response.to_json), filename: 'response.json')
      response_data.save
    else
      # Initialize a new Response record
      new_response = Response.new
      new_response.response_type = "route"
      new_response.json_file.attach(io: StringIO.new(response.to_json), filename: 'response.json')
      new_response.save
    end
  
    render json: { status: 'OK', routes: all_routes, barriers: barrier_coordinates }
  end

  def save_directions
    # Retrieve the file from the request
    directions_file = params[:directions_file]

    # Create a new ActiveStorage blob
    blob = ActiveStorage::Blob.create_and_upload!(
      io: directions_file,
      filename: directions_file.original_filename,
      content_type: directions_file.content_type
    )

    # Check if a Response record already exists
    response =  Response.where(response_type: "direction").last
   
    if response.present?
      # If a response exists, update it with the new blob
      response.response_type = "direction"
      response.json_file.attach(blob)
    else
      # If no response exists, create a new one and attach the blob
      response = Response.new
      response.response_type = "direction"
      response.json_file.attach(blob)
    end

    if response.save
      render json: { message: 'Directions file saved successfully' }, status: :ok
    else
      render json: { error: 'Failed to save directions file' }, status: :unprocessable_entity
    end
  end

  private

  def fetch_route(origin, destination, waypoints = nil)
    query_params = {
      origin: origin,
      destination: destination,
      key: Rails.application.credentials.staging[:google_maps_api_key],
      alternatives: true
    }
    query_params[:waypoints] = "optimize:true|#{waypoints}" if waypoints.present?
  
    response = HTTParty.get('https://maps.googleapis.com/maps/api/directions/json', {
      query: query_params
    })
    JSON.parse(response.body)
  end
  

  def check_admin_role
    unless current_user&.admin?
      redirect_to user_home_index_path, alert: 'Access Denied. You must be an admin to perform this action.'
    end
  end

  def get_kmz_extract_lat_long_region
    kmz_file = Kmz.last
    kmz_attachment = kmz_file.kmz_attachment
    data = []
    # Assuming kmz_attachment is an instance of ActiveStorage::Attached::One
    kmz_file = kmz_attachment.download
  
    # Use RubyZip to extract KML file from KMZ archive
    Zip::File.open_buffer(kmz_file) do |zip_file|
      zip_file.each do |entry|
        # Check if the entry is the KML file
        if File.extname(entry.name) == '.kml'
          kml_data = entry.get_input_stream.read
          doc = Nokogiri::XML(kml_data)
          # Iterate through Placemark elements
          doc.xpath('//kml:Placemark', 'kml' => 'http://www.opengis.net/kml/2.2').each do |placemark|
            coordinates = placemark.at_xpath('.//kml:Point/kml:coordinates', 'kml' => 'http://www.opengis.net/kml/2.2')&.text
  
            if coordinates
              # Split the coordinates into latitude, longitude, and altitude
              longitude, latitude, _ = coordinates.split(',')

              # Assuming you have some way to determine the region, replace 'determine_region_method' with the actual method
              region = determine_region_method(placemark)
  
              data << {latitude: latitude.to_f, longitude: longitude.to_f, region: region}
            end
          end
        end
      end
    end
  
    # Now you have the latitudes, longitudes, and regions extracted from the KML file
    data
  end

  def determine_region_method(placemark)
      structure_name = placemark.at_xpath('.//kml:SimpleData[@name="Structure Name"]', 'kml' => 'http://www.opengis.net/kml/2.2')&.text
      tmr_district = placemark.at_xpath('.//kml:SimpleData[@name="TMR District"]', 'kml' => 'http://www.opengis.net/kml/2.2')&.text
  
      return tmr_district if structure_name && tmr_district
      ''
  end

  def fetch_regions_for_permanent_barriers
    Barrier.all.map do |barrier|
      {
        latitude: barrier.latitude,
        longitude: barrier.longitude,
        region: barrier.name
      }
    end
  end

  def fetch_regions_for_government_barriers
    kmz_file = Kmz.last
    kmz_contents = kmz_file.kmz_attachment
    all_locations = get_kmz_extract_lat_long_region
    all_locations.uniq { |location| location[:region] }
  end

  def format_barriers_response(data)
    data.map do |lat, long, name|
      {
        latitude: lat,
        longitude: long,
        region: name
      }
    end
  end

  def hash_response(input_data)
    input_data.map do |hash|
      {
        latitude: hash["latitude"],
        longitude: hash["longitude"],
        region: hash["region"]
      }
    end
  end

  def get_locations(selected_regions, all_locations)
    gov_data = []

app/controllers/user/home_controller.rb
class User::HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @locations = []

    render 'index'
  end

  def geocode
    result = Geocoder.search(params[:address]).first
    coordinates = { latitude: result.latitude, longitude: result.longitude }

    render json: coordinates
  end

  def get_directions
    start_location =  params[:start_location]
    end_location = params[:end_location]

    barrier_coordinates = []
 
    response = HTTParty.get('https://maps.googleapis.com/maps/api/directions/json', {
      query: {
        origin: start_location,
        destination: end_location,
        key: Rails.application.credentials.staging[:google_maps_api_key],
        alternatives: true
      }
    })

    all_routes = response['routes']

    # Tesing code for Google api
    # directions_response = File.read('/home/bacancy/rails_work/AB-CRANE-HIRE/test/directions_response.json')

    # directions_data = JSON.parse(directions_response)
    # all_routes = directions_data['routes']

    render json: { status: 'OK', routes: all_routes, barriers: barrier_coordinates }
  end

  def job_sheet
    @directions = params[:start_location]
    render 'shared/job_sheet'
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/user/home_helper.rb
module User::HomeHelper
end

app/views/admin/home/_upload_form.html.erb
<%= form_with(url: admin_upload_kmz_path, method: 'post', local: true, multipart: true, data: { turbo_frame: 'upload-form-container' }) do |form| %>
  <%= form.file_field :kmz_file %>
  <%= form.submit 'Upload KMZ File' %>
<% end %>

app/views/admin/home/barriers.html.erb
<section class="form_main">
  <div class="container-fluid">
    <div class="row">
      <div class= "col-md-10 mx-auto">
        <p class="text-center bg-black text-white p-2 w-100 mb-0 fw-bold fs-3">
          BARRIERS
        </p>
      </div>
    </div>
    <div class="box_main">
      <div class="row">
        <div class="col-md-10 mx-auto">
          <div class="box_inner_child">
            <ul class="nav nav-tabs p-2" id="myTab" role="tablist">
              <li class="nav-item text-center" role="presentation">
                <button class="nav-link w-100" id="home-tab" data-bs-toggle="tab"
                  data-bs-target="#home" type="button" role="tab" aria-controls="home"
                  aria-selected="true">AUTO</button>
              </li>
              <li class="nav-item text-center ms-auto" role="presentation">
                <button class="nav-link active w-100" id="profile-tab" data-bs-toggle="tab"
                  data-bs-target="#profile" type="button" role="tab" aria-controls="profile"
                  aria-selected="false">PERMANENT</button>
              </li>
            </ul>
            <div class="tab-content" id="myTabContent">
              <div class="tab-pane fade" id="home" role="tabpanel"
                aria-labelledby="home-tab">
                <h2 class='text-start'><span class="fw-bold me-5">AUTO BARRIERS</span>
                  Manage all of your AUTO Barriers
                  below 
                </h2>
                <p class=" text-dark fs-6 px-2 mt-3 ">Browse your computer for the new government KMZ file to update Auto
                  Barriers: NB This will deactivate all current Auto Barriers.
                </p>
                
                <%= form_with(url: admin_upload_kmz_path, method: 'post', local: true, multipart: true, data: { turbo_frame: 'upload-form-container' }) do |form| %>
                  <div class="box position-relative">
                    <div class="row">
                      <div class="col-md-8 mx-auto">
                        <div class="form-group">
                          <%= form.file_field :kmz_file, class: "file", id: "kmz-file" %>
                          <div class="input-group mb-3">
                            <%= form.text_field :placeholder, disabled: true, class: "form-control rounded-0", placeholder: "Upload File", "aria-label" => "Upload File", "aria-describedby" => "basic-addon1" %>
                            <div class="input-group-append">
                              <button type="button" class="browse input-group-text btn btn-upload ms-3" id="browse-button">Browse</button>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="col-md-8 text-center mx-auto">
                        <%= form.submit 'Process File', class: "btn btn-secondary rounded-0 mx-auto" %>
                      </div>
                    </div>
                  </div>
                <% end %>               
              </div>
              <div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                <h2 class='text-start'><span class="fw-bold me-5">PERMANENT BARRIERS</span>
                  Manage all of your Permanent Barriers
                  below 
                </h2>
                <div id="error-message"></div>
                <div class="box text-start">
                  <%= render 'admin/barriers/form', barrier: @barrier %>               
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<%= javascript_include_tag 'barriers' %>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const fileInput = document.getElementById('kmz-file');
    const browseButton = document.getElementById('browse-button');
    const newBarrierForm = document.getElementById('new-barrier-form');
    const errorMessageContainer = document.getElementById('error-message');

    browseButton.addEventListener('click', function() {
      fileInput.click();
    });

    fileInput.addEventListener('change', function() {
      const fileName = fileInput.files[0] ? fileInput.files[0].name : 'Upload File';
      document.getElementById('kmz-file').nextElementSibling.querySelector('input').value = fileName;
    });

    document.addEventListener('DOMContentLoaded', function() {
      const newBarrierForm = document.getElementById('new-barrier-form');
    
      newBarrierForm.addEventListener('submit', function(event) {
        event.preventDefault();
    
        const formData = new FormData(event.target);
    
        fetch(event.target.action, {
          method: 'POST',  // Explicitly specify the method
          body: formData,
          headers: {
            'Accept': 'text/javascript',
            'X-CSRF-Token': Rails.csrfToken()
          }
        }).then(response => {
          if (response.ok) {
            // Request succeeded, handle the response
            return response.text();
          } else {
            // Request failed, handle the error
            throw new Error('Failed to add barrier');
          }
        }).then(responseText => {
          // Handle the response text (this could be success or error message)
          console.log(responseText);
        }).catch(error => {
          // Handle any errors during the fetch
          console.error(error);
        });
      });
    });
    
  });
</script>

app/views/admin/home/route_setting.html.erb
<body style="background-color: #fff !important;">
  <div class="w-100">
    <p class="mb-0 text-center p-3 fs-2 text-white bg-dark">
      ROUTE SETTINGS
    </p>
  </div>
  <section class="form_main mt-0">
    <div class="container-fluid">
      <div class="box_main">
        <div class="row">
          <div class="col-md-12 mx-auto">
            <div class="box_inner_child">
              <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                  <h2 class="text-start"><span class="fw-bold me-5">Route Settings</span> Configure the Route Settings
                    Below
                  </h2>
                  <p class="text-dark fs-6 px-2 mt-3 text-start">All of these fields will be on the generated job
                    sheet
                  </p>
                  <div class="box">
                    <form>
                      <div class="row">
                        <div class="col-md-6">
                          <div class="mb-3 form-check ps-0 ">
                            <h3 class="fs-6 text-start fw-bold ">Include Barriers:</h3>
                            <div class="d-flex mb-2">
                              <input type="checkbox" class="form-check-input d-block float-none ms-0 me-2"
                                id="governmentBarrierCheckbox">
                              <label class="form-check-label" for="governmentBarrierCheckbox">Government Barriers</label>
                            </div>
                            <div class="d-flex">
                              <input type="checkbox" class="form-check-input d-block float-none ms-0 me-2"
                                id="permanentBarrierCheckbox">
                              <label class="form-check-label" for="permanentBarrierCheckbox">Permanent Barriers</label>
                            </div>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="mb-3">
                            <h3 class="fs-6 text-start fw-bold">Barriers Regions:</h3>
                            <label for="exampleInputPassword1" class="form-label fw-light">Select the Regions barriers
                              you want to include in your route</label>
                            <div id="barriersRegions">
                              <!-- Regions will be dynamically loaded here -->
                            </div>
                          </div>
                        </div>
                      </div>
                      <button id="saveButton"
                        class="mt-5 btn add_btn w-100 p-2 p-lg-2fw-bold text-white rounded-0">Save</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <div id="barriersResults">
    <!-- Results will be displayed here -->
  </div>
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <script>
    var jq = jQuery.noConflict();

    var selectedGovernmentCheckboxes = [];
    var selectedPermanentCheckboxes = [];

    jq(document).ready(function () {
      function updateRegions(selectedCheckboxes) {
        var regionsContainer = jq('#barriersRegions');
        regionsContainer.empty();

        jq.ajax({
          url: '/admin/home/fetch_regions',
          method: 'GET',
          data: { checkboxes: selectedCheckboxes },
          dataType: 'json',
          success: function (data) {
            var regionDropdown = jq('<select multiple name="regions[]" class="form-select"></select>');
            jq.each(data, function (index, location) {
              regionDropdown.append('<option value="' + location.region + '">' + location.region + '</option>');
            });

            regionsContainer.append(regionDropdown);

            regionDropdown.trigger('change');
          },
          error: function (error) {
            console.error('Error fetching regions:', error);
          }
        });
      }

      jq('#governmentBarrierCheckbox').change(function () {
        if (this.checked) {
          selectedGovernmentCheckboxes.push('government');
        } else {
          selectedGovernmentCheckboxes = selectedGovernmentCheckboxes.filter(type => type !== 'government');
        }
        updateRegions([...selectedGovernmentCheckboxes, ...selectedPermanentCheckboxes]);
        updateResults('Barriers');
      });

      jq('#permanentBarrierCheckbox').change(function () {
        if (this.checked) {
          selectedPermanentCheckboxes.push('permanent');
        } else {
          selectedPermanentCheckboxes = selectedPermanentCheckboxes.filter(type => type !== 'permanent');
        }
        updateRegions([...selectedGovernmentCheckboxes, ...selectedPermanentCheckboxes]);
      });

      function handleSaveButton() {
        var selectedRegionValues = jq('#barriersRegions select[name="regions"]').val();
        console.log(selectedRegionValues.join(', '));
      }

      jq('#saveButton').on('click', function () {
        handleSaveButton();
        window.location.reload();
      });
    });
  </script>
</body>