config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    get 'home/index', to: 'home#index', as: 'home_index'
    get 'home/barriers', to: 'home#barriers', as: 'home_barriers'
    get 'home/job_sheet', to: 'home#job_sheet', as: 'job_sheet'
    get 'home/route_setting', to: 'home#route_setting', as: 'route_setting'
    get 'home/fetch_regions', to: 'home#fetch_regions', as: 'fetch_regions'
    post 'home/selected_regions', to: 'home#selected_regions', as: 'selected_regions'
    get 'home/geocode', to: 'home#geocode', as: 'geocode'
    post '/upload_kmz', to: 'kmz#upload'
    post '/barriers', to: 'barriers#create', format: :js
    get '/barriers', to: 'barriers#index', as: 'barrier_index'
    delete '/barriers', to: 'barriers#destroy', as: 'destroy'
    post '/job_sheets', to: 'job_sheets#create'
    post '/generate_pdf', to: 'job_sheets#generate_pdf'
    get 'home/get_directions', to: 'home#get_directions'
    post 'home/save_directions', to: 'home#save_directions'
  end

  namespace :user do
    get 'home/index', to: 'home#index', as: 'home_index'
    get 'home/geocode', to: 'home#geocode', as: 'geocode'
    get 'home/get_directions', to: 'home#get_directions'
    get 'home/job_sheet', to: 'home#job_sheet', as: 'job_sheet'
  end

  authenticated :admin do
    root to: 'admin/home#index', as: :authenticated_admin_root
  end

  authenticated :user do
    root to: 'user/home#index', as: :authenticated_user_root
  end

  unauthenticated do
    root to: 'user/home#index'
  end
end

app/models/job_sheet.rb
class JobSheet < ApplicationRecord
end

app/controllers/admin/job_sheets_controller.rb
class Admin::JobSheetsController < ApplicationController
  include ApplicationHelper

  def index
    @job_sheets = JobSheet.all
  end

  def new
    @job_sheet = JobSheet.new
  end

  def create
    @job_sheet = JobSheet.new(job_sheet_params)

    if @job_sheet.save
      redirect_to admin_job_sheets_path, notice: 'Job Sheet created successfully.'
    else
      render :new
    end
  end
  
  def generate_pdf
    @job_sheet = JobSheet.create!(job_sheet_params)
    
    data = fetch_directions

    response = Response.where(response_type: "direction").last
    json_data = response.json_file.download

    directions_data = JSON.parse(json_data)

    if data[:success]
      @directions = directions_data.split('<strong><h2>DIRECTION<h2/></strong>').reject(&:empty?).map { |route| route.split('<br>').reject(&:empty?).map(&:strip) }

      @route_polylines = data[:data].map { |route| route[:polyline] }
    else
      @directions = []
      @route_polylines = []
    end

    map_image_path = google_maps_image(@job_sheet.start_address, @job_sheet.end_address, @route_polylines)

    # Specify the destination directory within assets/images
    destination_directory = Rails.root.join('app', 'assets', 'images')

    # Ensure the destination directory exists or create it
    FileUtils.mkdir_p(destination_directory) unless File.directory?(destination_directory)

    # Move the image to the destination directory
    destination_path = File.join(destination_directory, 'map_image.png')
    FileUtils.mv(map_image_path, destination_path)

    respond_to do |format|
      format.html

      format.pdf do
        pdf_content = render_to_string(
          pdf: 'post_pdf',
          template: 'admin/job_sheets/generate_pdf',
          layout: 'pdf_layout',
          locals: { map_image_path: destination_path }
        )
        send_data(pdf_content, filename: 'post_pdf.pdf', type: 'application/pdf', disposition: 'inline')
      end
    end
  end
  
  private
  
  def job_sheet_params
    params.require(:job_sheet).permit(:start_address, :end_address, :customer_name, :site_contact, :contact_number, :notes, :job_number, :job_instruction)
  end

  def fetch_directions
    response =  Response.where(response_type: "route").last
    json_data = response.json_file.download
    directions_data = JSON.parse(json_data)

    if directions_data.all? { |data| data['status'] == 'OK' }
      # Parse the response to extract all routes with their instructions
      routes_with_instructions = parse_directions_response(directions_data)
      { success: true, data: routes_with_instructions }
    else
      { success: false, error_message: 'Failed to fetch directions' }
    end
  end
  
  def parse_directions_response(directions_data)
    routes_with_instructions = []
    directions_data.each do |data|
      next unless data['status'] == 'OK'
      data['routes'].each do |route|
        routes_with_instructions << {
          polyline: route['overview_polyline']['points'],
          instructions: extract_instructions(route['legs'].first)
        }
      end
    end
    routes_with_instructions
  end
  
  def extract_instructions(leg)
    instructions = []
    leg['steps'].each do |step|
      instructions << step['html_instructions']
    end
    instructions
  end
end

app/views/admin/job_sheets/generate_pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Location Detail</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 20px;
      text-align: left;
    }

    .header .logo {
      text-align: right;
    }

    .details {
      margin-bottom: 50px;
    }

    .info {
      margin-top: 20px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
    }

    th, td {
      border: 1px solid #ddd;
      padding: 8px;
      text-align: left;
    }

    th {
      background-color: #f2f2f2;
    }

    .map {
      page-break-before: always;
    }
  </style>
</head>
<body>
<div class="header">
  <div class="logo">
    <img src="/assets/logo.jpg" alt="Logo" class="logo"> <!-- Adjust the path to your logo -->
  </div>
  <div class="details">
    <h1>Location Detail</h1>
    <div class="info">
      <p><strong>JOB LOCATION:</strong></br> <%= @job_sheet.start_address %> to <%= @job_sheet.end_address %></p>
      <p><strong>CUSTOMER NAME:</strong> <%= @job_sheet.customer_name %></p>
      <p><strong>SITE CONTACT:</strong> <%= @job_sheet.site_contact %></p>
      <p><strong>CONTACT NUMBER:</strong> <%= @job_sheet.contact_number %></p>
      <p><strong>JOB NUMBER:</strong> <%= @job_sheet.job_number %></p>
      <p><strong>NOTES:</strong></br><%= @job_sheet.job_instruction %></p>
    </div>
  </div>
</div>

<h3>DIRECTIONS</h3>
<% @directions.each_with_index do |route_instructions, route_index| %>
  <br><h3><strong>Route <%= route_index + 1 %></strong></h3>
  <table>
    <thead>
      <tr>
        <th>Step</th>
        <th>Instruction</th>
      </tr>
    </thead>
    <tbody>
      <% route_instructions.each_with_index do |direction, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= direction.html_safe %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<div class="map">
  <h2>MAP:</h2>
  <%= image_tag 'map_image.png', alt: 'Map' %>
</div>
</body>
</html>

app/views/admin/job_sheets/index.html.erb
<!-- app/views/admin/job_sheets/index.html.erb -->

<h1>Job Sheets</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Start Address</th>
      <th>End Address</th>
      <th>Customer Name</th>
    </tr>
  </thead>
  <tbody>
    <% @job_sheets.each do |job_sheet| %>
      <tr>
        <td><%= job_sheet.id %></td>
        <td><%= job_sheet.start_address %></td>
        <td><%= job_sheet.end_address %></td>
        <td><%= job_sheet.customer_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Job Sheet', new_admin_job_sheet_path %>
<%= link_to 'Generate PDF', generate_pdf_admin_job_sheets_path, class: 'btn btn-primary' %>

app/views/admin/job_sheets/new.html.erb
<!-- app/views/admin/job_sheets/new.html.erb -->

<%= form_with(model: [:admin, @job_sheet], url: admin_job_sheets_path) do |form| %>
  <div>
    <%= form.label :start_address %>
    <%= form.text_field :start_address %>
  </div>

  <div>
    <%= form.label :end_address %>
    <%= form.text_field :end_address %>
  </div>

  <div>
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name %>
  </div>

  <%= form.submit %>
<% end %>