config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    get 'home/index', to: 'home#index', as: 'home_index'
    get 'home/barriers', to: 'home#barriers', as: 'home_barriers'
    get 'home/job_sheet', to: 'home#job_sheet', as: 'job_sheet'
    get 'home/route_setting', to: 'home#route_setting', as: 'route_setting'
    get 'home/fetch_regions', to: 'home#fetch_regions', as: 'fetch_regions'
    post 'home/selected_regions', to: 'home#selected_regions', as: 'selected_regions'
    get 'home/geocode', to: 'home#geocode', as: 'geocode'
    post '/upload_kmz', to: 'kmz#upload'
    post '/barriers', to: 'barriers#create', format: :js
    get '/barriers', to: 'barriers#index', as: 'barrier_index'
    delete '/barriers', to: 'barriers#destroy', as: 'destroy'
    post '/job_sheets', to: 'job_sheets#create'
    post '/generate_pdf', to: 'job_sheets#generate_pdf'
    get 'home/get_directions', to: 'home#get_directions'
    post 'home/save_directions', to: 'home#save_directions'
  end

  namespace :user do
    get 'home/index', to: 'home#index', as: 'home_index'
    get 'home/geocode', to: 'home#geocode', as: 'geocode'
    get 'home/get_directions', to: 'home#get_directions'
    get 'home/job_sheet', to: 'home#job_sheet', as: 'job_sheet'
  end

  authenticated :admin do
    root to: 'admin/home#index', as: :authenticated_admin_root
  end

  authenticated :user do
    root to: 'user/home#index', as: :authenticated_user_root
  end

  unauthenticated do
    root to: 'user/home#index'
  end
end

app/models/barrier.rb
class Barrier < ApplicationRecord
  validates :name, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  before_validation :set_default_enabled_value

  private

  def set_default_enabled_value
    self.enabled ||= false
  end
end

app/controllers/admin/barriers_controller.rb
class Admin::BarriersController < ApplicationController
  before_action :set_barrier, only: [:show, :edit, :update]

  def index
    @barriers = Barrier.all
  end

  def show
  end

  def new
    @barrier = Barrier.new
  end

  def create
    @barrier = Barrier.find_or_initialize_by(barrier_params)
  
    respond_to do |format|
      if @barrier.persisted?
        format.html { redirect_to admin_home_index_path(create_barrier: true), notice: 'Barrier already exists.' }
        format.js { render js: "window.location = '#{admin_home_index_path(create_barrier: true)}';" }
      elsif @barrier.save
        format.html { redirect_to admin_home_index_path(create_barrier: true), notice: 'Barrier created successfully.' }
        format.js { render js: "window.location = '#{admin_home_index_path(create_barrier: true)}';" }
      else
        format.js { render 'admin/barriers/error', status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if @barrier.update(barrier_params)
      redirect_to admin_barrier_path(@barrier), notice: 'Barrier was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    selected_ids = params[:selected_ids]

    Barrier.destroy_by(id: selected_ids) if selected_ids.present?
    redirect_to admin_home_index_path(create_barrier: true), notice: 'Selected barriers deleted successfully.'
  end

  private

  def set_barrier
    @barrier = Barrier.find(params[:id])
  end

  def barrier_params
    params.require(:barrier).permit(:name, :latitude, :longitude, :size, :enabled)
  end
end

app/views/admin/barriers/_error_message.html.erb
<p class="text-danger fs-6 px-2 mt-3">
  ERROR: Unable to add new Barrier. Please check all details and try again.
  Confirm Longitude and Latitude are valid.
</p>

app/views/admin/barriers/_form.html.erb
<%= form_for(Barrier.new, url: admin_barriers_path, id: 'new-barrier-form', html: {id: 'new-barrier-form'}, remote: true) do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" do %>
      Restriction/Road Name:
    <% end %>
    <%= form.text_field :name, class: "form-control rounded-0", id: "exampleInputEmail1", "aria-describedby" => "emailHelp" %>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :latitude, class: "form-label" do %>
          Latitude:
        <% end %>
        <%= form.text_field :latitude, class: "form-control rounded-0", id: "exampleInputPassword1" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :longitude, class: "form-label" do %>
          Longitude:
        <% end %>
        <%= form.text_field :longitude, class: "form-control rounded-0", id: "exampleInputPassword1" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :restriction_size, class: "form-label" do %>
          Restriction Size:
        <% end %>
        <%= form.text_field :size, class: "form-control rounded-0", id: "exampleInputPassword1" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3 form-check ps-0">
        <%= form.label :enabled, class: "form-check-label" do %>
          Enabled:
        <% end %>
        <%= form.check_box :enabled, class: "form-check-input d-block float-none ms-0 mt-2", id: "exampleCheck1" %>
      </div>
    </div>
  </div>
  <%= form.button 'ADD', class: "btn add_btn w-100 p-2 p-lg-2 fw-bold text-white rounded-0", type: 'submit' %>
<% end %>

<button id="manageButton" class="btn add_btn w-100 p-2 p-lg-2 bg-blue fw-bold text-white mt-3 rounded-0" type="button">MANAGE</button>

<div id="error-message"></div>

<script>
  $(document).ready(function() {
    $('#manageButton').on('click', function() {
      window.location.href = '<%= admin_barrier_index_path %>';
    });
  });
</script>

<script>
$(document).ready(function() {
  $('#new-barrier-form').on('ajax:beforeSend', function() {
    console.log('Form submission started...');
  });

  $('#new-barrier-form').on('ajax:success', function(event) {
    console.log('Form submission successful.');
    var data = event.detail[0];
    if (data.success) {
      window.location.href = '<%= admin_home_index_path(create_barrier: true) %>';
    } else {
      console.error('Error in form submission:', data.errors);
    }
  });

  $('#new-barrier-form').on('ajax:error', function(event) {
    console.error('Error in AJAX request:', event.detail[0]);
  });
});

</script>

app/views/admin/barriers/create.js.erb
const newBarrier = {
  name: '<%= j @barrier.name %>',
  latitude: <%= @barrier.latitude %>,
  longitude: <%= @barrier.longitude %>,
  size: <%= @barrier.size %>,
  enabled: <%= @barrier.enabled %>
};

// Add the new marker to the map
const color = newBarrier.enabled ? 'green' : 'red';
const newMarker = L.circleMarker([newBarrier.latitude, newBarrier.longitude], {
  color: color,
  radius: newBarrier.size
}).addTo(map);

// Add a popup with the barrier name
newMarker.bindPopup(newBarrier.name);

document.getElementById('error-message').innerHTML = '<%= j render 'shared/errors', resource: @barrier %>';

app/views/admin/barriers/error.js.erb
document.getElementById('error-message').innerHTML = '<%= j render 'shared/errors', resource: @barrier %>';

app/views/admin/barriers/index.html.erb
<h1>Manage Barriers</h1>

<%= form_tag admin_destroy_path, method: :delete, id: 'delete-form' do %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Restriction Size</th>
        <th>Enabled</th>
        <th>Select</th>
      </tr>
    </thead>
    <tbody>
      <% @barriers.each do |barrier| %>
        <tr>
          <td><%= barrier.name %></td>
          <td><%= barrier.latitude %></td>
          <td><%= barrier.longitude %></td>
          <td><%= barrier.size %></td>
          <td><%= barrier.enabled ? 'Yes' : 'No' %></td>
          <td><%= check_box_tag 'selected_ids[]', barrier.id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= button_tag 'DELETE SELECTED', type: 'button', class: 'btn btn-danger  mb-3', id: 'delete-selected' %> 
  <%= link_to 'Back', authenticated_admin_root_path, class: 'btn btn-secondary mb-3' %>
<% end %>

<div id="error-message"></div>

<script>
  $(document).ready(function() {
    $('#delete-selected').on('click', function() {
      // Ensure at least one checkbox is checked before submitting the form
      if ($('input[name="selected_ids[]"]:checked').length > 0) {
        $('#delete-form').submit();
      } else {
        // Show an error message if no checkboxes are checked
        $('#error-message').text('Please select at least one item to delete.');
      }
    });
  });
</script>